version: '3'

services:
    nginx:
      build: ./nginx
      image: nginx:1.15-alpine
      volumes:
        - static_volume:/usr/src/app/_static
        - media_volume:/usr/src/app/_media
      ports:
        - 80:80
      depends_on:
        - web
    web:
      build: .
      command: gunicorn do_it_django_prj.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/usr/src/app/_static
        - media_volume:/usr/src/app/_media
        - ./:/usr/src/app
      expose:
        - 8000
      environment:
        - POSTGRES_USER=do_it_django_db_user
        - POSTGRES_PASSWORD=do_it_django_db_password
        - POSTGRES_DB=do_it_django_dev
      depends_on:
        - db
    db:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume: